# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Anton's Gohugo Theme"
license = "MIT"
description = "A blog theme used by me"
homepage = "https://github.com/afberg"
min_version = 0.30.2

[author]
  name = "Anton Forsberg"
  homepage = "https://github.com/afberg"
